In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.linear_model import Ridge

In [2]:
df = pd.read_csv("08-Linear-Regression-Models/Advertising.csv")
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
X= df.drop('sales',axis=1)
y=df['sales']

In [4]:

polyConverter = PolynomialFeatures(degree=3,include_bias=False)
polyfeats = polyConverter.fit_transform(X)


In [5]:
X_train, X_test, y_train, y_test = train_test_split(polyfeats, y, test_size=0.3, random_state=101)

In [6]:
X_train[0]

array([1.93200000e+02, 1.84000000e+01, 6.57000000e+01, 3.73262400e+04,
       3.55488000e+03, 1.26932400e+04, 3.38560000e+02, 1.20888000e+03,
       4.31649000e+03, 7.21142957e+06, 6.86802816e+05, 2.45233397e+06,
       6.54097920e+04, 2.33555616e+05, 8.33945868e+05, 6.22950400e+03,
       2.22433920e+04, 7.94234160e+04, 2.83593393e+05])

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
#X_test = scaler.fit(X_test)


In [8]:
ridge_model = Ridge(alpha=10)
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [9]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [10]:
test_preds = ridge_model.predict(X_test)

In [11]:
mae = mean_absolute_error(y_test,test_preds)

In [12]:
mae

0.9670410375853887

In [13]:
rmse = np.sqrt(mean_squared_error(y_test,test_preds))

In [14]:
rmse

1.3327611545386242

In [15]:
from sklearn.linear_model import RidgeCV

In [16]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1, 10),scoring='neg_mean_squared_error')

In [17]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_squared_error')

In [18]:
ridge_cv_model.alpha_

0.1

In [19]:
from sklearn.metrics import SCORERS

In [20]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_s

In [21]:
test_preds = ridge_cv_model.predict(X_test)

In [22]:
mae = mean_absolute_error(y_test,test_preds)
rmse = np.sqrt(mean_squared_error(y_test,test_preds))

In [23]:
mae

0.9873965312408585

In [24]:
rmse

1.1676689886043725

In [25]:
from sklearn.linear_model import LassoCV

In [36]:
lasso_cv_model = LassoCV(eps=.1,n_alphas=100,cv=5)

In [37]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [38]:
lasso_cv_model.alpha_

0.4943070909225832

In [39]:
test_preds = lasso_cv_model.predict(X_test)

In [40]:
mae = mean_absolute_error(y_test,test_preds)
rmse = np.sqrt(mean_squared_error(y_test,test_preds))

In [44]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])